version: "1"

services:
  mechgacha:
    image: "hillexed/mechgacha"
    build: .
    #environment:
    #  - TOKEN=...
    volumes:
      - db_data:/root/mechgacha/db_data
    env_file: ".env"

volumes:
    db_data:
        external: true
